# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51bf5ba2ab701f25636df6da55e2e68073a55ab2f87323184b4cc5b104185f101e4863a5b65d58521936f427d6641c4ff0b46ad338370fe4eb5c3eaa96711827

test:
  secret_key_base: 3a7a2a51602d24c3721b6deb9af7111b0fc9e60b61237c08b2b9f393860766ecd83062a649cc2d7bcba3aee26d6b779a379075b30a0db76442235cb7c82ad5a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
